version: "3.9"
services:

  db:
    image: mysql:8.0.27
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: test_db
      MYSQL_USER: go_test
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306

  api:
    build: api/
    ports:
      - 8080:8080
    depends_on:
      - db